### ISSUE TITLE
pw_batt_reserve

### ISSUE THREAD

**Issue by Johnnexto** [atbore-phx/sbam#47]
For consideration; 
For me it looks like the pw_batt_reserve is checked every time when run. (Cron schedule)
This will result in the battery is charged to pw_batt_reserve, and repeated next cron run, resulting that the battery is charged and discharged before the energy is needed and  have to be recharged again on next cron, I guess it will be more efficient to charge the pv_batt_reserve based on the following; (I can't code, just playing with GPT)

if pw_batt < pw_batt_reserve and current_time < (end_hr - (pw_batt_reserve / max_charge)):
   
# True
    handle_low_battery_condition()
else:
    # Alternative
    normal_operation()
end_hr - (pw_batt_reserve / max_charge)

# Calculation of within time limit
time_limit = end_hr - (pw_batt_reserve / max_charge)

# Check both 
if pw_batt < pw_batt_reserve and current_time < time_limit:
    print("Activate reserve-logikk")
   case pw_batt < pw_batt_reserve: // battery is less than reserve => charge
else:
    print("Normal run")

OR:
Add hours for when charge pv_batt_reserve is allowed to run?

Appreciate all good work you have done!

<img width="1149" alt="Skjermbilde 2024-12-06 kl  15 13 01" src="https://github.com/user-attachments/assets/3bead234-c1bf-4977-9217-85998416e207">

{"level":"info","ts":"2024-12-05T03:15:01+01:00","msg":"Starting Calculate PV production for solar System 0"}
{"level":"info","ts":"2024-12-05T03:15:01+01:00","msg":"Forecast Solar Power for 5/12/2024: 42586 Wh"}
{"level":"info","ts":"2024-12-05T03:15:02+01:00","msg":"Starting Calculate PV production for solar System 1"}
{"level":"info","ts":"2024-12-05T03:15:02+01:00","msg":"Forecast Solar Power for 5/12/2024: 8890 Wh"}
{"level":"info","ts":"2024-12-05T03:15:02+01:00","msg":"Total Forecast Solar Power for 5/12/2024: 51477 Wh"}
{"level":"info","ts":"2024-12-05T03:15:02+01:00","msg":"Battery Capacity to charge: 31617 Wh"}
{"level":"info","ts":"2024-12-05T03:15:02+01:00","msg":"Battery Capacity Max: 33177 Wh"}
{"level":"info","ts":"2024-12-05T03:15:02+01:00","msg":"your Daily consumption is:56000 Wh"}
{"level":"info","ts":"2024-12-05T03:15:02+01:00","msg":"battery 1559.319000 Wh < reserve 4800.000000 Wh"}
{"level":"info","ts":"2024-12-05T03:15:02+01:00","msg":"Setting Fronius Storage Force Charge at 9%"}
{"level":"debug","ts":"2024-12-05T03:15:02+01:00","msg":"Reading register: 40361 ; value: 1; default:"}
{"level":"debug","ts":"2024-12-05T03:15:02+01:00","msg":"Reading register: 40349 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-05T03:15:02+01:00","msg":"Reading register: 40356 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-05T03:15:02+01:00","msg":"Reading register: 40357 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-05T03:15:02+01:00","msg":"Reading register: 40351 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-05T03:15:02+01:00","msg":"Writing register: 40361 ; value: 1"}
{"level":"debug","ts":"2024-12-05T03:15:02+01:00","msg":"Writing register: 40349 ; value: 2"}
{"level":"debug","ts":"2024-12-05T03:15:02+01:00","msg":"Writing register: 40356 ; value: 64636"}
{"level":"debug","ts":"2024-12-05T03:15:02+01:00","msg":"Writing register: 40357 ; value: 10000"}
{"level":"debug","ts":"2024-12-05T03:15:02+01:00","msg":"Writing register: 40351 ; value: 0"}
{"level":"info","ts":"2024-12-05T03:15:02+01:00","msg":"Setting Fronius Storage Force Charge done."}
{"level":"info","ts":"2024-12-05T04:15:01+01:00","msg":"Starting Calculate PV production for solar System 0"}
{"level":"info","ts":"2024-12-05T04:15:01+01:00","msg":"Forecast Solar Power for 5/12/2024: 42586 Wh"}
{"level":"info","ts":"2024-12-05T04:15:02+01:00","msg":"Starting Calculate PV production for solar System 1"}
{"level":"info","ts":"2024-12-05T04:15:02+01:00","msg":"Forecast Solar Power for 5/12/2024: 8890 Wh"}
{"level":"info","ts":"2024-12-05T04:15:02+01:00","msg":"Total Forecast Solar Power for 5/12/2024: 51477 Wh"}
{"level":"info","ts":"2024-12-05T04:15:02+01:00","msg":"Battery Capacity to charge: 28930 Wh"}
{"level":"info","ts":"2024-12-05T04:15:02+01:00","msg":"Battery Capacity Max: 33177 Wh"}
{"level":"info","ts":"2024-12-05T04:15:02+01:00","msg":"your Daily consumption is:56000 Wh"}
{"level":"info","ts":"2024-12-05T04:15:02+01:00","msg":"battery 4246.656000 Wh < reserve 4800.000000 Wh"}
{"level":"info","ts":"2024-12-05T04:15:02+01:00","msg":"Setting Fronius Storage Force Charge at 1%"}
{"level":"debug","ts":"2024-12-05T04:15:02+01:00","msg":"Reading register: 40351 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-05T04:15:02+01:00","msg":"Reading register: 40361 ; value: 1; default:"}
{"level":"debug","ts":"2024-12-05T04:15:02+01:00","msg":"Reading register: 40349 ; value: 2; default:"}
{"level":"debug","ts":"2024-12-05T04:15:02+01:00","msg":"Reading register: 40356 ; value: 64636; default:"}
{"level":"debug","ts":"2024-12-05T04:15:02+01:00","msg":"Reading register: 40357 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-05T04:15:02+01:00","msg":"Writing register: 40351 ; value: 0"}
{"level":"debug","ts":"2024-12-05T04:15:02+01:00","msg":"Writing register: 40361 ; value: 1"}
{"level":"debug","ts":"2024-12-05T04:15:02+01:00","msg":"Writing register: 40349 ; value: 2"}
{"level":"debug","ts":"2024-12-05T04:15:02+01:00","msg":"Writing register: 40356 ; value: 65436"}
{"level":"debug","ts":"2024-12-05T04:15:02+01:00","msg":"Writing register: 40357 ; value: 10000"}
{"level":"info","ts":"2024-12-05T04:15:02+01:00","msg":"Setting Fronius Storage Force Charge done."}
{"level":"info","ts":"2024-12-05T05:15:01+01:00","msg":"Starting Calculate PV production for solar System 0"}
{"level":"info","ts":"2024-12-05T05:15:01+01:00","msg":"Forecast Solar Power for 5/12/2024: 42529 Wh"}
{"level":"info","ts":"2024-12-05T05:15:02+01:00","msg":"Starting Calculate PV production for solar System 1"}
{"level":"info","ts":"2024-12-05T05:15:02+01:00","msg":"Forecast Solar Power for 5/12/2024: 8891 Wh"}
{"level":"info","ts":"2024-12-05T05:15:02+01:00","msg":"Total Forecast Solar Power for 5/12/2024: 51420 Wh"}
{"level":"info","ts":"2024-12-05T05:15:02+01:00","msg":"Battery Capacity to charge: 28598 Wh"}
{"level":"info","ts":"2024-12-05T05:15:02+01:00","msg":"Battery Capacity Max: 33177 Wh"}
{"level":"info","ts":"2024-12-05T05:15:02+01:00","msg":"your Daily consumption is:56000 Wh"}
{"level":"info","ts":"2024-12-05T05:15:02+01:00","msg":"battery 4578.426000 Wh < reserve 4800.000000 Wh"}
{"level":"info","ts":"2024-12-05T05:15:02+01:00","msg":"Setting Fronius Storage Force Charge at 0%"}
{"level":"info","ts":"2024-12-05T05:15:02+01:00","msg":"percent of charging is <1%, skipping Force Charge and set defaults."}
{"level":"info","ts":"2024-12-05T05:15:02+01:00","msg":"Setting Fronius Storage Defaults start..."}
{"level":"debug","ts":"2024-12-05T05:15:02+01:00","msg":"Reading register: 40349 ; value: 2; default:"}
{"level":"debug","ts":"2024-12-05T05:15:02+01:00","msg":"Reading register: 40356 ; value: 65436; default:"}
{"level":"debug","ts":"2024-12-05T05:15:02+01:00","msg":"Reading register: 40357 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-05T05:15:02+01:00","msg":"Reading register: 40351 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-05T05:15:02+01:00","msg":"Reading register: 40361 ; value: 1; default:"}
{"level":"debug","ts":"2024-12-05T05:15:02+01:00","msg":"Writing register: 40357 ; value: 10000"}
{"level":"debug","ts":"2024-12-05T05:15:02+01:00","msg":"Writing register: 40351 ; value: 0"}
{"level":"debug","ts":"2024-12-05T05:15:02+01:00","msg":"Writing register: 40361 ; value: 1"}
{"level":"debug","ts":"2024-12-05T05:15:02+01:00","msg":"Writing register: 40349 ; value: 0"}
{"level":"debug","ts":"2024-12-05T05:15:02+01:00","msg":"Writing register: 40356 ; value: 10000"}
{"level":"info","ts":"2024-12-05T05:15:02+01:00","msg":"Setting Fronius Modbus Defaults done."}
{"level":"info","ts":"2024-12-05T05:15:02+01:00","msg":"Setting Fronius Storage Force Charge done."}
{"level":"info","ts":"2024-12-05T06:15:00+01:00","msg":"Starting Calculate PV production for solar System 0"}
{"level":"info","ts":"2024-12-05T06:15:00+01:00","msg":"Forecast Solar Power for 5/12/2024: 42174 Wh"}
{"level":"info","ts":"2024-12-05T06:15:02+01:00","msg":"Starting Calculate PV production for solar System 1"}
{"level":"info","ts":"2024-12-05T06:15:02+01:00","msg":"Forecast Solar Power for 5/12/2024: 8909 Wh"}
{"level":"info","ts":"2024-12-05T06:15:02+01:00","msg":"Total Forecast Solar Power for 5/12/2024: 51084 Wh"}
{"level":"info","ts":"2024-12-05T06:15:02+01:00","msg":"Battery Capacity to charge: 31252 Wh"}
{"level":"info","ts":"2024-12-05T06:15:02+01:00","msg":"Battery Capacity Max: 33177 Wh"}
{"level":"info","ts":"2024-12-05T06:15:02+01:00","msg":"your Daily consumption is:56000 Wh"}
{"level":"info","ts":"2024-12-05T06:15:02+01:00","msg":"Battery is under the reserve and Net Power (battery reserve + Net solar power) is not enough: -115.450000 Wh"}
{"level":"info","ts":"2024-12-05T06:15:02+01:00","msg":"Setting Fronius Storage Force Charge at 0%"}
{"level":"info","ts":"2024-12-05T06:15:02+01:00","msg":"percent of charging is <1%, skipping Force Charge and set defaults."}
{"level":"info","ts":"2024-12-05T06:15:02+01:00","msg":"Setting Fronius Storage Defaults start..."}
{"level":"debug","ts":"2024-12-05T06:15:02+01:00","msg":"Reading register: 40357 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-05T06:15:02+01:00","msg":"Reading register: 40351 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-05T06:15:02+01:00","msg":"Reading register: 40361 ; value: 1; default:"}
{"level":"debug","ts":"2024-12-05T06:15:02+01:00","msg":"Reading register: 40349 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-05T06:15:02+01:00","msg":"Reading register: 40356 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-05T06:15:02+01:00","msg":"Writing register: 40361 ; value: 1"}
{"level":"debug","ts":"2024-12-05T06:15:02+01:00","msg":"Writing register: 40349 ; value: 0"}
{"level":"debug","ts":"2024-12-05T06:15:02+01:00","msg":"Writing register: 40356 ; value: 10000"}
{"level":"debug","ts":"2024-12-05T06:15:02+01:00","msg":"Writing register: 40357 ; value: 10000"}
{"level":"debug","ts":"2024-12-05T06:15:02+01:00","msg":"Writing register: 40351 ; value: 0"}
{"level":"info","ts":"2024-12-05T06:15:02+01:00","msg":"Setting Fronius Modbus Defaults done."}
{"level":"info","ts":"2024-12-05T06:15:02+01:00","msg":"Setting Fronius Storage Force Charge done."}
{"level":"info","ts":"2024-12-05T07:15:01+01:00","msg":"Starting Calculate PV production for solar System 0"}
{"level":"info","ts":"2024-12-05T07:15:01+01:00","msg":"Forecast Solar Power for 5/12/2024: 41750 Wh"}
{"level":"info","ts":"2024-12-05T07:15:02+01:00","msg":"Starting Calculate PV production for solar System 1"}
{"level":"info","ts":"2024-12-05T07:15:02+01:00","msg":"Forecast Solar Power for 5/12/2024: 8956 Wh"}
{"level":"info","ts":"2024-12-05T07:15:02+01:00","msg":"Total Forecast Solar Power for 5/12/2024: 50706 Wh"}
{"level":"info","ts":"2024-12-05T07:15:02+01:00","msg":"Battery Capacity to charge: 31518 Wh"}
{"level":"info","ts":"2024-12-05T07:15:02+01:00","msg":"Battery Capacity Max: 33177 Wh"}
{"level":"info","ts":"2024-12-05T07:15:02+01:00","msg":"your Daily consumption is:56000 Wh"}
{"level":"info","ts":"2024-12-05T07:15:02+01:00","msg":"Battery is under the reserve and Net Power (battery reserve + Net solar power) is not enough: -493.100000 Wh"}
{"level":"info","ts":"2024-12-05T07:15:02+01:00","msg":"Setting Fronius Storage Force Charge at 1%"}
{"level":"debug","ts":"2024-12-05T07:15:02+01:00","msg":"Reading register: 40361 ; value: 1; default:"}
{"level":"debug","ts":"2024-12-05T07:15:02+01:00","msg":"Reading register: 40349 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-05T07:15:02+01:00","msg":"Reading register: 40356 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-05T07:15:02+01:00","msg":"Reading register: 40357 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-05T07:15:02+01:00","msg":"Reading register: 40351 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-05T07:15:02+01:00","msg":"Writing register: 40351 ; value: 0"}
{"level":"debug","ts":"2024-12-05T07:15:02+01:00","msg":"Writing register: 40361 ; value: 1"}
{"level":"debug","ts":"2024-12-05T07:15:02+01:00","msg":"Writing register: 40349 ; value: 2"}
{"level":"debug","ts":"2024-12-05T07:15:02+01:00","msg":"Writing register: 40356 ; value: 65436"}
{"level":"debug","ts":"2024-12-05T07:15:02+01:00","msg":"Writing register: 40357 ; value: 10000"}
{"level":"info","ts":"2024-12-05T07:15:02+01:00","msg":"Setting Fronius Storage Force Charge done."}
{"level":"info","ts":"2024-12-05T07:55:00+01:00","msg":"Setting Fronius Storage Defaults start..."}
{"level":"debug","ts":"2024-12-05T07:55:00+01:00","msg":"Reading register: 40361 ; value: 1; default:"}
{"level":"debug","ts":"2024-12-05T07:55:00+01:00","msg":"Reading register: 40349 ; value: 2; default:"}
{"level":"debug","ts":"2024-12-05T07:55:00+01:00","msg":"Reading register: 40356 ; value: 65436; default:"}
{"level":"debug","ts":"2024-12-05T07:55:00+01:00","msg":"Reading register: 40357 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-05T07:55:00+01:00","msg":"Reading register: 40351 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-05T07:55:00+01:00","msg":"Writing register: 40356 ; value: 10000"}
{"level":"debug","ts":"2024-12-05T07:55:00+01:00","msg":"Writing register: 40357 ; value: 10000"}
{"level":"debug","ts":"2024-12-05T07:55:00+01:00","msg":"Writing register: 40351 ; value: 0"}
{"level":"debug","ts":"2024-12-05T07:55:00+01:00","msg":"Writing register: 40361 ; value: 1"}
{"level":"debug","ts":"2024-12-05T07:55:00+01:00","msg":"Writing register: 40349 ; value: 0"}
{"level":"info","ts":"2024-12-05T07:55:00+01:00","msg":"Setting Fronius Modbus Defaults done."}

**Comment by atbore-phx** [comment]
Hi @Johnnexto,

Thanks for bringing up this issue!

You're correct that SBAM is checking battery charge conditions every cycle, which can lead to frequent charging and discharging if the battery level is hovering around the target.

To reduce this behavior, I suggest implementing a hysteresis logic.

We can configure two thresholds (as percentages of the target charge) to avoid this charge/discharge cycling. For example, if the target charge is 3000 Wh:

Upper threshold: 110% of the target (3300 Wh)

Lower threshold: 90% of the target (2700 Wh)


With hysteresis logic in place:

Charging will stop when the battery reaches 3300 Wh (110% of the target).

Discharging will stop when the battery drops to 2700 Wh (90% of the target).


These thresholds can be adjusted to suit specific needs, allowing flexibility in controlling the charge/discharge behavior.

The hysteresis logic could be applied to both reserve and general changing mechanisms.

What do you think of this approach?

**Comment by Johnnexto** [comment]
Thank you for addressing this!
Your approach is better, as I understand this will work as follows;
ie: 
forecast_pv > pw_consumtion, battery is charged to pw_batt_reserve and discharge of battery is set to not allowed (by OutWRte, or StorCtrl_Mod=0x09 manual, idle?) 
and reset at end_hr (when defaults are written back or if more charging is required next cycle ie. due to change of forecast_pv energy needed) further the reserve is checked according to crontab if limits is within pw_batt_reserve +/- 10% 

Do I understand you correctly? If so it would be very useful to have it implemented. 
I think avoiding use the pw_batt_reserve before end_hr is a huge benefit.

**Comment by atbore-phx** [comment]
> forecast_pv > pw_consumtion, battery is charged to pw_batt_reserve and discharge of battery is set to not allowed (by OutWRte, or StorCtrl_Mod=0x09 manual, idle?)
it's different the logic is here:

**Comment by atbore-phx** [comment]
forecast_pv > pw_consumtion, battery is charged to pw_batt_reserve and discharge of battery is set to not allowed (by OutWRte, or StorCtrl_Mod=0x09 manual, idle?)
it's different the logic is here: https://github.com/atbore-phx/sbam/blob/60a76d7f40434f2be28bcbd8ee48de3dac5b4f7b/pkg/fronius/schedule.go#L7

i don't propose to change the charge logic but just to introduce hysteresys to prevent frequently charge/discharge trotteling.

**Comment by atbore-phx** [comment]
> To avoid the pw_batt_reserve is used during that period I need to add "Max discharge power rule 0 W" from 04-08 and disable rule in march, to allow for 100% self-sufficiency.

exactly, i do the same for the winter but on a different time range.
Sure feel free to share

**Comment by Johnnexto** [comment]
Thanks, 
I will have a look if it's possible to add a flow in node red to do the pw_batt_reserve (I am pretty sure it is, just have to figure out how to.) to do have reserve power available at the time I need it. (I will share if I succeed)
SBAM works perfectly as it is with forecast and charging, very thankful for all your work done!
Here is my plant if you want to have a look:
https://www.solarweb.com/Home/GuestLogOn?pvSystemId=4aa6364f-ac73-4382-8e5d-a6e8151812a6

**Comment by atbore-phx** [comment]
@Johnnexto, I'm glad you like sbam ;) enjoy.
I've planned this issue for v.1.4.0 (January 2025) to implement hysteresis logic.

**Comment by Johnnexto** [comment]
When implementing the hysteris logic, would it also be an idea to add a "PW_battery_reserve_chargestarttime"?, just to control when the reserve is charged? if not set, charge reserve needed at every cron run. If time set, charge of reserve is checked against system time. ie: cron 0 03,04,05,06,07 * * 1-5 and "PW_battery_reserve_chargestarttime" = 05:59, the charge of the reserve is started and included on the 06:00 cron run? (and also the later ones) Just an idea.. 😄

**Comment by atbore-phx** [comment]
Hi @Johnnexto,  

sure, I understand your point I'll create two variables:  

- `PW_battery_reserve_charge_start_hr` (if empty default: `start_hr`)  
- `PW_battery_reserve_charge_end_hr` (if empty default: `end_hr`)  

These will be exposed in the add-on configuration to allow customization.  

For every crontab occurrence `t`, if the `PW_battery_reserve` is not met, SBAM will charge the reserve only when:  
`start_hr <= PW_battery_reserve_charge_start_hr <= t <= PW_battery_reserve_charge_end_hr <= end_hr`.  

Let me know if this aligns with your expectations.

i'll also add this point in  [V1.4.0](https://github.com/atbore-phx/sbam/milestone/3)

**Comment by Johnnexto** [comment]
That is perfect! 🤩

**Comment by Johnnexto** [comment]
@atbore-phx 

If internet connection or solcast is offline, PW_battery_reserve charging is not performed.
May you consider to add post error message and let script continue running to do the PW_battery_reserve charge?

s6-rc: info: service legacy-services successfully started
{"level":"debug","ts":"2025-01-08T06:00:16+01:00","msg":"Debug Logs activated: true"}
Running, press ctrl+c to exit...
{"level":"error","ts":"2025-01-08T07:00:08+01:00","msg":"Error getting forecast for https://api.solcast.com.au/rooftop_sites/4492-72ca-9e36-3368/forecasts?format=json : Get \"https://api.solcast.com.au/rooftop_sites/4492-72ca-9e36-3368/forecasts?format=json\": dial tcp: lookup api.solcast.com.au on 127.0.0.11:53: server misbehaving","stacktrace":"sbam/pkg/power.(*Power).Handler\n\t/home/runner/work/sbam/sbam/pkg/power/handler.go:30\nsbam/pkg/cmd.schedule\n\t/home/runner/work/sbam/sbam/pkg/cmd/schedule.go:213\nsbam/pkg/cmd.crontabSchedule.func1\n\t/home/runner/work/sbam/sbam/pkg/cmd/schedule.go:244\ngithub.com/robfig/cron/v3.FuncJob.Run\n\t/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136\ngithub.com/robfig/cron/v3.(*Cron).startJob.func1\n\t/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312"}
{"level":"error","ts":"2025-01-08T07:00:08+01:00","msg":"Get \"https://api.solcast.com.au/rooftop_sites/4492-72ca-9e36-3368/forecasts?format=json\": dial tcp: lookup api.solcast.com.au on 127.0.0.11:53: server misbehaving","stacktrace":"sbam/pkg/cmd.schedule\n\t/home/runner/work/sbam/sbam/pkg/cmd/schedule.go:215\nsbam/pkg/cmd.crontabSchedule.func1\n\t/home/runner/work/sbam/sbam/pkg/cmd/schedule.go:244\ngithub.com/robfig/cron/v3.FuncJob.Run\n\t/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136\ngithub.com/robfig/cron/v3.(*Cron).startJob.func1\n\t/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312"}
panic: Get "https://api.solcast.com.au/rooftop_sites/4492-72ca-9e36-3368/forecasts?format=json": dial tcp: lookup api.solcast.com.au on 127.0.0.11:53: server misbehaving
goroutine 33 [running]:
sbam/pkg/cmd.schedule({0x4000024097, 0x20}, {0x4000026004, 0xa5}, {0x400002206b, 0xc}, 0x40f01d0000000000, 0x40bd4c0000000000, 0x40b2c00000000000, {0x400000e089, ...}, ...)
	/home/runner/work/sbam/sbam/pkg/cmd/schedule.go:216 +0x2a8
sbam/pkg/cmd.crontabSchedule.func1()
	/home/runner/work/sbam/sbam/pkg/cmd/schedule.go:244 +0x50
github.com/robfig/cron/v3.FuncJob.Run(0x0?)
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x24
github.com/robfig/cron/v3.(*Cron).startJob.func1()
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x5c
created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 21
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0x90
s6-rc: info: service legacy-services: stopping

**Comment by atbore-phx** [comment]
> [@atbore-phx](https://github.com/atbore-phx)
> 
> If internet connection or solcast is offline, PW_battery_reserve charging is not performed. May you consider to add post error message and let script continue running to do the PW_battery_reserve charge?

open https://github.com/atbore-phx/sbam/issues/52

**Comment by atbore-phx** [comment]
@Johnnexto, the time reserve battery logic has been implemented in this PR #56. I'll continue with testing and documentation in the coming days. We are on schedule to complete by the end of January.
